### PR TITLE
Upgrade libraries to use in application with common packages

### PR DESCRIPTION
**Pull request by AlirezaDaryani**
When I need to use this package in my app, it was impossible to upgrade common packages.
for example I want to use package_info_plus: ^3.0.2 in my app but it was impossible because `app_review` used old versions of that.
Here is updated packages in yaml file:

```
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7
```

### CODE REVIEW

**Comment by yutae** [comment]
@rodydavis Please check this PR 🙏

**Comment by techwnn** [comment]
I think you can add your dependencies in your yaml.
Since app_review use package_info_plus: ^3.0.1, you can use any version of package_info_plus between 3.0.1 and 4.0.0.

**Review by rodydavis — APPROVED** [review]
LGTM

**Comment by doubleo2** [comment]
@rodydavis There are five open PRs all of which are variations of the same thing: updating `package_info_plus`. It took 18 months for you to review this PR and despite getting your nod of approval, it's still unclear how this gets merged and released.

How do we move this package forward?

**Comment by rodydavis** [comment]
Part of the intention of moving the package to Flutter Community would be that I didn't have to block on releases.

That being said, I reviewed the PR and LGTM 👍🏼

**Review by rodydavis — APPROVED** [review]
LGTM

**Comment by rodydavis** [comment]
There are some conflicts that need to be resolved before merging. I’ll watch this and when it is ready I’ll merge and publish

**Comment by AlirezaDaryani** [comment]
The conflict has been fixed, But I'm not sure if it is useful anymore...

**Pull request merged**
